// Central configuration (env-overridable).
const MIN = 60 * 1000;
const H = 60 * MIN;
const D = 24 * H;

export const config = {
  port: Number(process.env.PORT) || 8080,

  // Bind to localhost by default: the server is only reachable through the
  // reverse proxy / tunnel on the same host, never directly from the internet.
  // (The Android emulator's 10.0.2.2 also maps to the host loopback, so local
  //  dev still works.) Set HOST=0.0.0.0 only if you really need LAN exposure.
  host: process.env.HOST || '127.0.0.1',

  // data.gouv dataset "Liste des radars fixes en France".
  // We query the API to always pick the latest published CSV resource.
  radarDatasetApiUrl:
    process.env.RADAR_DATASET_API_URL ||
    'https://www.data.gouv.fr/api/1/datasets/liste-des-radars-fixes-en-france/',

  // How often to re-check data.gouv for a fresh dataset (ms). Default: daily.
  refreshIntervalMs: Number(process.env.REFRESH_INTERVAL_MS) || 24 * 60 * 60 * 1000,

  // Routing engine, proxied by /api/route. Defaults to the free public OSRM
  // demo server (hosted, no self-host, no key). Override with OSRM_URL to point
  // at a self-hosted OSRM or another OSRM-compatible endpoint later.
  osrmUrl: process.env.OSRM_URL || 'https://router.project-osrm.org',

  // OpenRouteService: preferred routing provider when a key is set (better quality,
  // supports avoiding tolls/motorways). Falls back to OSRM when ORS_API_KEY is absent.
  orsApiKey: process.env.ORS_API_KEY || null,
  orsUrl: process.env.ORS_URL || 'https://api.openrouteservice.org',

  // Road signs from OpenStreetMap (Overpass). Cached to stay within rate limits.
  overpassUrl: process.env.OVERPASS_URL || 'https://overpass-api.de/api/interpreter',
  signDefaultRadiusM: 30000, // 30 km
  signMaxRadiusM: 120000, // 120 km
  signTimeoutS: 30,
  signMaxElements: 8000,
  // Preloaded OSM France signs dataset (generated by scripts/extract-signs.sh).
  // When present, it's used instead of live Overpass — fast, complete, offline.
  signDataFile: process.env.SIGN_DATA_FILE || './data/signs.ndjson',
  // Level crossings (SNCF open data, GeoJSON). Loaded next to the OSM signs.
  levelCrossingFile: process.env.LEVEL_CROSSING_FILE || './data/liste-des-passages-a-niveau.geojson',
  signGridDeg: 0.02, // ~2.2 km spatial-index cells
  signRouteBufferM: 60,
  signLimitMaxDistM: 90, // max distance to a sampled speed point for "the limit here"
  // Persistent per-cell disk cache — the Overpass fallback when no dataset is present.
  signCacheDir: process.env.SIGN_CACHE_DIR || './data/signs-cache',
  signCellDeg: 0.05,
  signCacheTtlMs: 14 * 24 * 60 * 60 * 1000, // 14 days
  signMaxCells: 60, // nearest cells returned per request (from cache)
  signMaxFetchPerReq: 6, // new Overpass fetches per request (rest fill as you drive)

  // Safety caps for query endpoints (radius is user-tunable up to 1000 km).
  maxNearRadiusM: 1_000_000,
  defaultNearRadiusM: 3000,
  maxResults: 5000,
  // Radars "on the trip" (POST /api/radars/route): how far from the route line a radar
  // still counts. Fixed-radar coordinates sit beside the carriageway, not on it.
  radarRouteBufferM: 150,
  radarRouteMaxBufferM: 500,
  // Load everything within 90 km, but shrink to 40 km where it's ultra-dense
  // (too many points around the driver) to keep the map light.
  denseRadiusM: 40000,
  denseCountThreshold: 300,

  // Nearby places (stations, bornes, parkings…) via Overpass. No fixed perimeter:
  // the search widens through these rings until it has enough results.
  placeRadiiM: [5000, 20000, 60000, 200000],
  placeLimit: 20,
  placeTimeoutS: 25,
  placeCacheTtlMs: 10 * MIN,
  // Overpass rejects anonymous clients (406): identify ourselves.
  placeUserAgent: process.env.PLACE_USER_AGENT || 'x_radar/1.0 (+https://debian.taila9954f.ts.net)',

  // Official fuel prices — prix-carburants.gouv.fr "flux instantané" (Licence Ouverte).
  // They only enrich the fuel stations the nearby search finds; they never replace it.
  fuelFeedUrl: process.env.FUEL_FEED_URL || 'https://donnees.roulez-eco.fr/opendata/instantane',
  fuelRefreshIntervalMs: Number(process.env.FUEL_REFRESH_INTERVAL_MS) || 10 * MIN,
  fuelRetryMs: MIN,
  fuelGridDeg: 0.01, // ~1 km cells
  // An OSM station tagged with an official id must still sit near that station.
  fuelRefMaxDistanceM: 1000,
  // Without an id: the nearest official station within this distance…
  fuelMatchMaxDistanceM: 200,
  // …unless a second one is nearly as close, in which case there is no match.
  fuelMatchAmbiguityM: 30,
  // Fuel stations kept from the Overpass answer the search already made, for a client
  // asking for a pool (?pool=1) to pick the nearest ones that show a price. No extra
  // request: the ring that found 20 stations usually holds many more in a city.
  fuelPoolLimit: 60,

  // Crowdsourced user reports (radar mobile, zone de contrôle, accident…).
  reportsFile: process.env.REPORTS_FILE || './data/reports.json',
  /**
   * Report scoring.
   *
   *   k          = ln(factors / minimumScore)
   *   timeScore  = factors × exp(-(k × age) / baseDurationMs)
   *
   * so a report is worth exactly `minimumScore` when it reaches `baseDurationMs`:
   * the base duration IS the lifetime, not a time constant.
   *
   * Confirmations and contradictions scale it instead of moving the clock:
   *   confirmationBonus     = min(1 + 0.10 × √confirmations, 1.40)
   *   contradictionPenalty  = 1 / (1 + 0.25 × √contradictions)
   *
   * That intrinsic score is what the server keeps and prunes on (< minimum = gone).
   * The driver-facing score multiplies it by road / direction / distance factors,
   * which depend on who is asking — see the app's ReportRelevance.
   *
   * `persistent` (a fixed camera) never decays and only an admin removes it.
   */
  reportScore: {
    // type              facteur   durée de vie          zone d'impact
    radar_mobile:    { factors: 70, baseDurationMs: 60 * MIN, impactM: 500 },
    control_zone:    { factors: 75, baseDurationMs: 90 * MIN, impactM: 1000 },
    voiture_radar:   { factors: 70, baseDurationMs: 60 * MIN, impactM: 500 },
    stopped_vehicle: { factors: 65, baseDurationMs: 45 * MIN, impactM: 500 },
    accident:        { factors: 90, baseDurationMs: 2 * H, impactM: 2000 },
    object_on_road:  { factors: 90, baseDurationMs: 60 * MIN, impactM: 1000 },
    traffic_jam:     { factors: 75, baseDurationMs: 30 * MIN, impactM: 3000 },
    damaged_road:    { factors: 80, baseDurationMs: 1 * D, impactM: 500 },
    roadworks:       { factors: 85, baseDurationMs: 7 * D, impactM: 1500 },
    slippery_road:   { factors: 75, baseDurationMs: 90 * MIN, impactM: 2000 },
    low_visibility:  { factors: 75, baseDurationMs: 60 * MIN, impactM: 2000 },
    road_crew:       { factors: 85, baseDurationMs: 60 * MIN, impactM: 1000 },
    wrong_way:       { factors: 95, baseDurationMs: 30 * MIN, impactM: 5000 },
    camera:          { factors: 65, baseDurationMs: null, impactM: 300, persistent: true },
    // Legacy "Danger", kept for the reports already stored.
    hazard:          { factors: 70, baseDurationMs: 60 * MIN, impactM: 1000 },
  },
  /** Below this a report is worthless and disappears. */
  reportScoreMinimum: 10,
  /** Confirmation bonus: 1 + step × √confirmations, capped. */
  reportConfirmStep: 0.10,
  reportConfirmCap: 1.40,
  /** Contradiction penalty: 1 / (1 + step × √contradictions). */
  reportContradictionStep: 0.25,
  /** Relevance bands handed to the app (below the minimum the report is deleted). */
  reportRelevance: { low: 10, normal: 30, high: 60 },
  /** How relevant a report on another road / another carriageway still is. */
  reportRoadFactor: { same: 1.0, other: 0.35 },
  reportDirectionFactor: { same: 1.0, unknown: 0.75, opposite: 0.15 },
  /** Stand-in lifetime for a persistent report (camera). */
  reportPermanentMs: 100 * 365 * D,

  // Who may create each report type (guest < client < admin).
  reportMinRole: {
    voiture_radar: 'client',
    camera: 'admin',
    radar_mobile: 'guest',
    control_zone: 'guest',
    accident: 'guest',
    hazard: 'guest',
    stopped_vehicle: 'guest',
    object_on_road: 'guest',
    traffic_jam: 'guest',
    damaged_road: 'guest',
    roadworks: 'guest',
    slippery_road: 'guest',
    low_visibility: 'guest',
    road_crew: 'guest',
    wrong_way: 'guest',
  },
  // A control zone covers a stretch of the reported lane, not a single point.
  controlZoneLengthM: 80,
  // Radar-car probable-zone aggregation (circle tightens with more reports).
  zoneBaseRadiusM: 2500,
  zoneMinRadiusM: 250,
  zoneMaxRadiusM: 4000,
  // Each confirm pushes the expiry out by this much; each deny pulls it in.
  reportConfirmExtendMs: 20 * 60 * 1000,
  reportDenyShortenMs: 30 * 60 * 1000,
  // A report is dropped once (denials - confirms) reaches this.
  reportDropScore: 3,
  reportMaxNearRadiusM: 1_000_000,
  reportDefaultNearRadiusM: 8000,

  // Speed-limit maintenance: drivers propose the limit a sign shows ("50 → 70"). The
  // proposals for one spot are scored with the report formula (reports/score.js) and the
  // limit only changes once they are strong enough; a change applied is permanent.
  speedLimitsFile: process.env.SPEED_LIMITS_FILE || './data/speed-limits.json',
  /** The limits a driver can pick: the ones the app draws as signs. */
  speedLimitValues: [20, 30, 50, 70, 80, 90, 100, 110, 130],
  /**
   * Same shape as reportScore. A proposal is worth `factors` and decays over
   * `baseDurationMs` from the last driver who proposed the same value: a sign does not go
   * away like an event, each new witness renews it. Drivers proposing anything else there
   * (the current limit included) are its contradictions.
   *
   * A proposal is applied when its score reaches the "high" relevance band, at least
   * `minSupporters` distinct people back it and they outnumber everyone else there:
   *   known   — the spot has a limit (OSM, radar VMA, an earlier change): 3 people, and
   *             one other opinion there takes 8 of them.
   *   unknown — nothing mapped there yet: 2 people fill the gap.
   * An admin's proposal is applied at once.
   */
  speedLimitScore: {
    known: { factors: 60, baseDurationMs: 60 * D, minSupporters: 3 },
    unknown: { factors: 70, baseDurationMs: 60 * D, minSupporters: 2 },
  },
  /** Proposals this close to one another, on the same way and from the same limit, are one change. */
  speedLimitGroupRadiusM: 250,
  /** An applied change replaces the mapped limit points this close to its supporters. */
  speedLimitZoneRadiusM: 150,
  /** Two courses closer than this run the same way (ReportRelevance's same-way angle). */
  speedLimitSameWayDeg: 60,
  /** An applied change still wins over a mapped point up to this much nearer. */
  speedLimitOverrideTieM: 10,
  /** Proposals that never applied (expired, outdated, rejected) stay in the history this long. */
  speedLimitHistoryMs: 365 * D,
  speedLimitMinRole: 'guest',
  speedLimitDefaultNearRadiusM: 5000,
  speedLimitMaxNearRadiusM: 100000,

  // Accounts (identity + roles guest/client/admin).
  accountsFile: process.env.ACCOUNTS_FILE || './data/accounts.json',
  // A Guest gets the complete navigation experience for one week. Afterwards
  // the account stays signed in and can consult the map, but cannot start a trip.
  guestTrialMs: Number(process.env.GUEST_TRIAL_MS) || 7 * D,
  // A referral code grants this much Client access. Payments will use the same
  // subscription end date when the payment portal is added.
  referralSubscriptionMonths: Number(process.env.REFERRAL_SUBSCRIPTION_MONTHS) || 6,
  // Keep a useful but bounded server-side journey history per account.
  accountTripHistoryMax: Number(process.env.ACCOUNT_TRIP_HISTORY_MAX) || 200,
  // Admin API token. Admin endpoints are DISABLED unless this is set (env).
  adminToken: process.env.ADMIN_TOKEN || null,
  // Session token lifetime (client/admin stay logged in).
  sessionTtlMs: 90 * 24 * 60 * 60 * 1000, // 90 days

  // SMTP for email verification + password reset (via env; disabled if unset).
  smtp: {
    host: process.env.SMTP_HOST || null,
    port: Number(process.env.SMTP_PORT) || 587,
    user: process.env.SMTP_USER || null,
    pass: process.env.SMTP_PASS || null,
    from: process.env.SMTP_FROM || 'x_radar',
  },
  resetCodeTtlMs: 30 * 60 * 1000, // 30 min
  // Guests are deleted after this long without launching the app.
  guestMaxAgeMs: 10 * 24 * 60 * 60 * 1000, // 10 days
  // Profile pictures: stored on the VPS filesystem, served statically at /avatars.
  avatarsDir: process.env.AVATARS_DIR || './data/avatars',
  avatarMaxBytes: 2 * 1024 * 1024, // 2 MB
  // Absolute base for avatar URLs the app loads (the public tunnel host).
  publicBaseUrl: (process.env.PUBLIC_BASE_URL || 'https://debian.taila9954f.ts.net').replace(/\/$/, ''),

  // Live users on the road (shared position; visible by default, invisible mode available).
  liveTtlMs: 90 * 1000, // a shared position is "live" for 90 s
  liveDefaultRadiusM: 20000,
  liveMaxRadiusM: 200000,
  liveMaxResults: 200,
};
